version: "3"
services:

  nginx:
    image: nginx:1-alpine
    extra_hosts:
    - "foo:127.0.0.1"
    ports:
      - "80:80"
    container_name: docker-demo_nginx

    volumes:
      - ./nginx/nginx.prod.cong:/etc/nginx/cong.d/nginx.conf
    depends_on:
      - frontend
      - api

  frontend:
    build: 
      context: ./frontend
      dockerfile: ./Dockerfile.prod
    container_name: realworld-docker-frontend
    command: npx serve -s build -l 4000
    restart: unless-stopped
    stdin_open: true
    tty: true

  api:
    build: ./api
    command: npm run start
    environment:
      - PORT=8080
      - HOST=http://localhost
      - MONGODB_URL=mongodb://api_db:27017/api
    depends_on:
      - api_db

  api_db:
    image: mongo:latest
    volumes:
      - ./mongodb_api:/data/db